.PHONY: all
all: tmux neovim eza starship fzf ripgrep gopls

.PHONY: tmux
tmux:
	cd tmux ; $(MAKE) ; cd -

.PHONY: neovim
neovim:
	cd neovim ; $(MAKE) ; cd -

.PHONY: eza
eza:
	cd eza ; $(MAKE) ; cd -

.PHONY: starship
starship:
	cd starship ; $(MAKE) ; cd -

.PHONY: fzf
fzf:
	cd fzf ; $(MAKE) ; cd -

.PHONY: ripgrep
ripgrep:
	cd ripgrep ; $(MAKE) ; cd -

.PHONY: gopls
gopls:
	cd gopls ; $(MAKE) ; cd -
