.PHONY: all
all: tmux neovim eza starship

.PHONY: tmux
tmux:
	cd tmux ; $(MAKE) ; cd -

.PHONY: neovim
neovim:
	cd neovim ; $(MAKE) ; cd -

.PHONY: eza
eza:
	cd eza ; $(MAKE) ; cd -

.PHONY: starship
starship:
	cd starship ; $(MAKE) ; cd -
