.PHONY: all
all: tmux neovim eza starship fzf ripgrep gopls jq zsh-syntax-highlighting zsh-completions zsh-autosuggestions

.PHONY: tmux
tmux:
	cd tmux ; $(MAKE) ; cd -

.PHONY: neovim
neovim:
	cd neovim ; $(MAKE) ; cd -

.PHONY: eza
eza:
	cd eza ; $(MAKE) ; cd -

.PHONY: starship
starship:
	cd starship ; $(MAKE) ; cd -

.PHONY: fzf
fzf:
	cd fzf ; $(MAKE) ; cd -

.PHONY: ripgrep
ripgrep:
	cd ripgrep ; $(MAKE) ; cd -

.PHONY: gopls
gopls:
	cd gopls ; $(MAKE) ; cd -

.PHONY: jq
jq:
	cd jq ; $(MAKE) ; cd -

.PHONY: zsh-syntax-highlighting
zsh-syntax-highlighting:
	cd zsh-syntax-highlighting ; $(MAKE) ; cd -

.PHONY: zsh-completions
zsh-completions:
	cd zsh-completions ; $(MAKE) ; cd -

.PHONY: zsh-autosuggestions
zsh-autosuggestions:
	cd zsh-autosuggestions ; $(MAKE) ; cd -
